### ISSUE TITLE
1.4.1-1.20.2 Incorrect modrinth version number

### ISSUE THREAD

**Issue by bonn2** [tr7zw/WaveyCapes#54]
The version number for both the Fabric and Forge release of 1.4.1-1.20.2 is set as 1.3.2 in Modrinth, this prevents automatic updaters from discovering this release and updating to it.

![image](https://github.com/tr7zw/WaveyCapes/assets/42011672/d42a6c4a-82f8-42d9-a97b-fc0612dc7d64)

**Comment by tr7zw** [comment]
Apparently, I forgot to change the versions inside the mod files during that release, causing that desync. I fixed them on modrinth, but cant say if this change will work. Also, the file ingame will still claim its 1.3.2, so potentially it will try to update the mod all the time 
![grafik](https://github.com/tr7zw/WaveyCapes/assets/5133936/90dbde63-a3f1-450e-ac42-2e2edd3951ba)
It will only be truly fixed with the next release.
