### ISSUE TITLE
1.21.1 Neo variant, crash when clicking the `Config` in mods list

### ISSUE THREAD

**Issue by 3gf8jv4dv** [tr7zw/WaveyCapes#66]
[Crash Report](https://gist.github.com/3gf8jv4dv/f6f82a71dcca66417764e8ea602d80a8)

**Comment by NovaViper** [comment]
Although I can't tell if OP's a bot, this is a real issue actually. In fact several founds recently I found have the exact same issue (I think it's because NeoForge changed their API somewhere during the beta and alpha builds of 1.21.0/1.21.1). I ran into the same issue where clicking on the config button in the mod menu makes the game crash. Running NeoForge v21.1.21 and WaveyCapes v1.4.9 in my case

Logs: https://mclo.gs/1GISJng

**Comment by tr7zw** [comment]
Known, will be auto fixed next time a release is done. Currently just don't want to make new releases for 1.16.5-1.21.1 fabric forge neoforge just to fix the config screen for 1.21.1 neoforge (especially seeing how 1.21.1 is entirely optional for the client).

**Comment by tr7zw** [comment]
Fixed with the release later today.
