### ISSUE TITLE
When I choose ‘Slim’ model, the cape doesn't show up

### ISSUE THREAD

**Issue by QuietDly** [tr7zw/WaveyCapes#70]
Minecraft 1.16.5; Fabric 0.16.5; Fabric API 0.42.0; Java 17.0.5

**Comment by tr7zw** [comment]
OK can reproduce in 1.16.5 fabric, but not 1.18.2 fabric. So seems like some issue with the backport/logic.

**Comment by tr7zw** [comment]
As an update: narrowed it down to the renderlayer not getting added to the slim player renderer. But during dev mode, it does work(which is why I never noticed that, since I don't play 1.16 anymore, just doing tests in dev mode). Comparing the 1.3.x builds with 1.4.x builds, I can't figure out why this is the case suddenly.

**Comment by tr7zw** [comment]
Added a dumb workaround
