### ISSUE TITLE
luner client issue

### ISSUE THREAD

**Issue by xsnaax** [tr7zw/WaveyCapes#79]
well i had the mod one a few days ago it worked just fine until it randomly just stoped working every time i open luner it just shows the mojang screen for ever i waited hours n it didnt work n i made sure its waveycapes n not any other mod is there a way to fix this? btw its on 1.21.1

**Comment by tr7zw** [comment]
Lunar is just taking people's mods without permission (like my 3d skin layers and replay mod) and then gets people to pay for overpriced cosmetics/"premium features". Their client is 100% never going to be supported for any of my mods. https://microcontrollersdev.github.io/Alternatives/1.8.9/lunar_client/

**Comment by xsnaax** [comment]
what other client do you suggest

**Comment by tr7zw** [comment]
It *was* under MIT license because I didn't expect anyone to disrespect devs this badly. Lunar didn't ask, managed to not ship the MIT license, didn't give credit, refused any attempts of me asking for any compensation for them just taking the mod like helping to backport to 1.8, refused to download it the official way from modrinth on install and refused my request to remove my mod from their client.
That's why many of my mods are no longer open source, so something like this can't happen again. This caused months of emotional anxiety and stress for me, so I will sure has heck not support their client. 
With replay mod they had a legal fight where they had to remove it for some time AFAIK, you'd have to Google for that.

**Comment by Phantom14600** [comment]
im sorry to hear that, thats completely valid. however will you end up deliberately making your mods to not work with lunar? or just not provide support for them.

**Comment by RoninscodeX** [comment]
Yeah I have a similar question will all of your mods just not work with lunar? Also you shouldn't have listed it under MIT and made it open source in the first place. Moonsworth isn't just a single mod developer so when they are able to cut corners without breaking any legal expectations they will do it. As for the cosmetics they are completely optional, but literally any company needs money to continue functioning. Now it sure isn't ethical but to some extent it was your fault, but I see now that you listed it under another license which is good. Also if it is open sourced and you aren't getting any money from it anyways so why are you upset that lunar included this mod in their licenses files (according to the other guy apparently) and credited it? But I guess copyright law is distinct from ethical principles so you can choose not to but as a lunar user who enjoys your mods and runs on a laptop, it is quite unfortunate that I can't use mods like exordium for performance and stuff like wavey capes for visuals or maybe even more of your mods in the future.

**Comment by tr7zw** [comment]
>  however will you end up deliberately making your mods to not work with lunar? or just not provide support for them.

Afaik they don't work, mainly because Lunar messes too much with mc while also trying to protect their code so no one dares to even read anything they made. I might in the future add something that prevents the mods from loading on lunar in the first place, idk, not looking to stir up this drama again, as I said, caused more than enough harm already. If it crashes naturally, that's fine.

> Also you shouldn't have listed it under MIT and made it open source in the first place.

Yep, its lesson's learned. Don't make stuff open source if you don't want a bigger fish to screw you over.

> Moonsworth isn't just a single mod developer so when they are able to cut corners without breaking any legal expectations they will do it.

Yea, and are actively hurting the community. Anyone supporting them by using the client and paying them money is hurting mod developers. 

> Also if it is open sourced and you aren't getting any money from it anyways

Devs do via Modrinth/Curseforge. I guess people don't realize how much time gets put into making Mods/ResourcePacks/Shaders/Modpacks, which wouldn't be doable without the support of Modrinth/Curseforge. Anyone using Lunar for 3d skin layers (or other mods they took like replay mod) and not Fabric/Forge/NeoForge/Quilt the normal way is causing a loss for the devs of said mods in revenue and downloads.
The open source license was chosen as a way to ensure the mod can be ported into the future in case I vanish for whatever reason. If I get hit by a car tomorrow, no one is legally allowed right now to make a version of 3d skin layers/EntityCulling/WaveyCapes etc. for 1.21.6 once it is out and put that on Modrinth/CurseForge. Many mods are still alive and ported, thanks to being open source. Bad actors like Moonsworth are destroying that. You can filter Modrinth to get a fun list of mods that could just stop updating at any point and then getting lost to time, thanks to the devs needing to be overly protecting against bad actors: https://modrinth.com/mods?l=open_source!=true

> why are you upset that lunar included this mod in their licenses files (according to the other guy apparently) and credited it?

a) They didn't even ask, I learned about the "honor" of my mod being in Lunar by a random user asking me for support on where a setting is
b) They DIDN'T include the license. I had to install their client in a VM and checked, turns out they forgot, till I send them a mail about it
c) They also initially didn't plan on crediting me in any way, that came later. (as a footnote in the patch notes afaik)
d) It was a long and drawn out talk on Twitter with the owner of Moonsworth which resulted in not much. Basically it was: "we got what we wanted, we are in the legal right, so screw you".

> But I guess copyright law is distinct from ethical principles

Yes, like I said, they are legally in the right, that's why I can't do shit about it other than ask people not to support their behavior and for example not waste my time trying to make my stuff work with their client. Same reason I don't support cracked mc like TLauncher.

Related: https://microcontrollersdev.github.io/Alternatives/1.8.9/lunar_client/ https://microcontrollersdev.github.io/Alternatives/latest/lunar/

**Comment by Phantom14600** [comment]
> > however will you end up deliberately making your mods to not work with lunar? or just not provide support for them.
> 
> Afaik they don't work, mainly because Lunar messes too much with mc while also trying to protect their code so no one dares to even read anything they made. I might in the future add something that prevents the mods from loading on lunar in the first place, idk, not looking to stir up this drama again, as I said, caused more than enough harm already. If it crashes naturally, that's fine.

Thanks, however please don't make it not load on lunar I really love your mods and while I think your decision to not make support for lunar is valid I feel like making all of them not work would be a bit too unnecessary.
